### ISSUE TITLE
TF 2.0 Compatibility 

### ISSUE THREAD

**Issue by shun-lin** [google/tf-quant-finance#12]
Hi!

Thanks for the really cool library! I recently came across this library as I want to learn more about quant finance and ML and this package really interested me :) I understand it's currently pre-Alpha but I am wondering if this package is compatible with TF 2.0, if not, is it somewhere on the roadmap or is that something I can help out with? Thank you so much!

**Comment by cyrilchim** [comment]
Hi Shun!

Thanks for reaching out. We believe most of the library should be TF2
-compatible.
We are currently working on open-sourcing the internal code and will ensure
compatibility shortly in version 0.1.

If you can see obvious flaws, please feel free to send a pull request.

Many thanks,
Cyril

**Comment by shun-lin** [comment]
Hi @cyrilchim thanks for the quick response! Definitely will keep an eye out for any flaws, thanks!

**Comment by cyrilchim** [comment]
Library should be TF2 compatible.
