### ISSUE TITLE
Baron-Adesi Whaley analytic approximation for American options

### ISSUE THREAD

**Issue by saxena-ashish-g** [google/tf-quant-finance#3]
American options have a number of approximate pricing formula under Black-Scholes. 
In particular, the [Baron-Adesi Whaley approximation](https://deriscope.com/docs/Barone_Adesi_Whaley_1987.pdf) is of interest.

The module implementing this method should live under [tf_quant_finance/volatility/american_option.py](https://github.com/google/tf-quant-finance/tree/master/tf_quant_finance/volatility). It should support both puts and calls. Tests should be in american_option_test.py in the same folder.

**Comment by kwonhur** [comment]
Hi, 
Can I work on this issue? Thanks

**Comment by cyrilchim** [comment]
Hi Kwon! Sure, I've assigned the issue to you. Please reach out if you have any questions. In case you need help getting started with TensorFlow, please refer to the [trainings](https://github.com/google/tf-quant-finance/blob/master/tf_quant_finance/examples/README.md)

**Comment by esztermarton** [comment]
Hey @cyrilchim - this looks cool, could I please give it a go? Thanks!

**Comment by cyrilchim** [comment]
This is now resolved! Thank you, Rebeka!
