### ISSUE TITLE
TypeError: Can't instantiate abstract class ExampleProcess with abstract methods fd_solver_backward, sample_paths

### ISSUE THREAD

**Issue by franz101** [google/tf-quant-finance#32]
Trying to run the example Monte_Carlo_Euler_Scheme.ipynb  I run into this error:
TypeError: Can't instantiate abstract class ExampleProcess with abstract methods fd_solver_backward, sample_paths

https://colab.research.google.com/github/google/tf-quant-finance/blob/master/tf_quant_finance/examples/jupyter_notebooks/Monte_Carlo_Euler_Scheme.ipynb#scrollTo=uG8UAZXjeUhf

**Comment by saxena-ashish-g** [comment]
Thanks for reporting this, Franz. We will take a look.

**Comment by cyrilchim** [comment]
The example is outdated. Will update shortly.

**Comment by franz101** [comment]
@cyrilchim @saxena-ashish-g  thanks for the super quick response ;)

**Comment by cyrilchim** [comment]
I have updated the [notebook](https://colab.sandbox.google.com/github/google/tf-quant-finance/blob/master/tf_quant_finance/examples/jupyter_notebooks/Monte_Carlo_Euler_Scheme.ipynb) and added Greek computation example. Please let me know if you have any further issues.
