### ISSUE TITLE
Missing FDAmericanEngine from quantlib in American_Option_Black_Scholes.ipynb

### ISSUE THREAD

**Issue by arthurpham** [google/tf-quant-finance#53]
> AttributeError: module 'QuantLib' has no attribute 'FDAmericanEngine'

According to the quantlib release https://github.com/lballabio/QuantLib/releases/tag/QuantLib-v1.22, FDAmericanEngine has been removed after being deprecated, and is replaced by FdBlackScholesVanillaEngine

**Comment by cyrilchim** [comment]
I have updated the colab with new timings and also with the updated method.
