### ISSUE TITLE
Month.md and month.md collide on case-insensitive filesystem

### ISSUE THREAD

**Issue by luweizheng** [google/tf-quant-finance#62]
Hi,

I have just cloned this project and find that Month.md and month.md in `api_docs/tf_quant_finance/datetime/` collide on my macOS. I could not pull recent merges. The best solution is to reformat my local APFS filesystem. But I think reformatting filesystem seems not a good choice.  I guess `api_docs` may be generated automatically. However, it would be nice if the api and the markdown file could change to another name. And it would benefit other developers who want to clone the project into their macOS filesystem.

Thanks!

**Comment by cyrilchim** [comment]
Hi,

Thanks for reporting this. I think you should still be able to compile the library as only api_docs folder is affected. 
You definitely should not reformat your drive because of this. I will update the api_doc generator to avoid name duplications.

Best,
Cyril

**Comment by cyrilchim** [comment]
Could you please check if this is still an issue?

**Comment by luweizheng** [comment]
> Could you please check if this is still an issue?

Thanks! I just re-clone the project. It seems to be ok now.

**Comment by cyrilchim** [comment]
Marking it as resolved
