### ISSUE TITLE
Pricing formulas for Barrier options under Black-Scholes

### ISSUE THREAD

**Issue by cyrilchim** [google/tf-quant-finance#7]
Formulas for pricing a Barrier option under Black-Scholes model is of interest. (See, e.g., Section 26.9 of Hull(2018), Options, Futures, and Other Derivatives, 9th edition).

The module implementing this method should live under tf_quant_finance/volatility/barrier_option.py. It should support both puts (up-and-in put, down-and-out put) and calls (down-in call, up-and-out call). Tests should be in barrier_option_test.py in the same folder.

**Comment by Patil2099** [comment]
@cyrilchim Can I work on this?

**Comment by cyrilchim** [comment]
@Patil2099 Could you please let us know if there is any progress on this?

**Comment by saxena-ashish-g** [comment]
@DevarakondaV

You might find [this](https://warwick.ac.uk/fac/soc/wbs/subjects/finance/research/wpaperseries/1994/94-54.pdf) paper useful (around page 20).

**Comment by DevarakondaV** [comment]
@saxena-ashish-g I think I can implement this. I'll give it a shot since @Patil2099 hasn't responded.

**Comment by cyrilchim** [comment]
Reassigned to @DevarakondaV . Thanks!

**Comment by DevarakondaV** [comment]
Is it expected that the model executes in both graph and eager mode?

**Comment by cyrilchim** [comment]
Yes, we expect that the user is able to build a graph

**Comment by cyrilchim** [comment]
Thanks, Vishnu! This is now [merged](https://github.com/google/tf-quant-finance/pull/31).

**Comment by DevarakondaV** [comment]
Hey @cyrilchim no problem! Just to let you know that I haven't committed the changes for xla compatibility yet. Additionally, I was still looking at [this](https://github.com/google/tf-quant-finance/pull/31#discussion_r435117425). Not sure if you still want me to continue with it?

**Comment by cyrilchim** [comment]
Oh, yes. Would you like to add an XLA test and ensure that both `continuous_dividends` and  `cost_of_carries` can be None?

**Comment by saxena-ashish-g** [comment]
Vishnu,

That (my comment about the dividends) is relatively minor so don't worry
about it if you haven't already put in time. We will fix it at a later
point. If you already have a fix, then please feel free to send another pr
and we will merge it.

Cheers,
Ashish

**Comment by DevarakondaV** [comment]
@cyrilchim and @saxena-ashish-g, I'll put in the pull request as soon as I can!

**Comment by cyrilchim** [comment]
To add to what Ashish says, if you have an XLA test, please feel free to send a change as that would be useful.
